name: Azure Pipelines
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted Ubuntu 1604
    steps:
    - task: CmdLine@2
      displayName: Install newman
      inputs:
        script: 'sudo npm install -y newman'
        workingDirectory: $(System.DefaultWorkingDirectory)
    - task: CmdLine@2
      displayName: Test starter APIs
      continueOnError: true
      inputs:
        script: 'newman run StarterAPIs.json'
        workingDirectory: $(System.DefaultWorkingDirectory)

    